# Generic Makefile for compiling Atmel AVR microcontroller firmware

# $Id$

AVRSRC		= ..

.PHONY: clean reallyclean distclean

include $(AVRSRC)/include/AVR.mk

clean: AVR_mk_clean

reallyclean: clean

distclean: reallyclean
