name=MuntsTech_LPC1114_IOP
version=1.0.0
author=Philip Munts <phil@munts.net>
maintainer=Philip Munts <phil@munts.net>
sentence=Raspberry Pi LPC1114 I/O Processor Expansion Board MUNTS-0004 driver.
paragraph=Supported board architectures are RP2040/RP2350, and STM32.
category=Other
url=https://git.munts.com/arm-mcu/arduino
architectures=avr,rp2040,stm32
depends=
includes=
