name=MuntsTech_Interfaces
version=1.0.1
author=Philip Munts <phil@munts.net>
maintainer=Philip Munts <phil@munts.net>
sentence=C++ abstract interface classes.
paragraph=Adapted from the Linux Simple I/O Library (https://github.com/pmunts/libsimpleio).
category=Other
url=https://git.munts.com/arm-mcu/arduino
architectures=*
depends=
includes=
