name=MuntsTech_AVR
version=1.0.0
author=Philip Munts <phil@munts.net>
maintainer=Philip Munts <phil@munts.net>
sentence=Make files and classes for AVR microcontroller boards.
paragraph=Supported boards are the Arduino Uno and Arduino Nano.
category=Other
url=https://git.munts.com/avr-mcmcu/arduino
architectures=avr
depends=
includes=
